name: web3-this-then-that

#
# chains
#

arbitrum:
  default_network: mainnet
  mainnet:
    default_provider: llamanodes

bsc:
  default_network: mainnet
  mainnet:
    default_provider: llamanodes

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: llamanodes

optimism:
  default_network: mainnet
  mainnet:
    default_provider: llamanodes

polygon:
  default_network: mainnet
  mainnet:
    default_provider: llamanodes

#
# end chains
#

plugins:
  - name: arbitrum
    version: 0.6.2
  - name: bsc
    version: 0.6.1
  - name: etherscan
    version: 0.6.9
  - name: llamanodes
    version: git+https://github.com/llamanodes/ape-llamanodes.git@main
  - name: optimism
    version: 0.6.2
  - name: polygon
    version: 0.6.5
  - name: tokens
    version: 0.6.2
