[package]
name = "web3-this-then-that"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
dotenv = "0.15.0"
ethers = { version = "2.0.2", features = ["rustls", "ws"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls-native-roots"], default-features = false }
tokio = { version = "1", features = ["full"] }
